### PR TITLE
add new cats

### PR DESCRIPTION
**Pull request by jenya-zhuchok**

### CODE REVIEW

**Review by tectonick — APPROVED** [review]
LGTM

**Comment by Himura2la** [comment]
LGTM

**Review by Himura2la — APPROVED** [review]
LGTM

**Review by rfoxxxy — APPROVED** [review]
LGTM

**Review by spherebread — APPROVED** [review]
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::cat::white_large_square::white_large_square::white_large_square::cat::cat::cat::cat::white_large_square::cat::cat::cat::white_large_square::cat::white_large_square::white_large_square::white_large_square::cat::white_large_square:
:white_large_square::cat::white_large_square::white_large_square::white_large_square::cat::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::cat::white_large_square::white_large_square::cat::cat::white_large_square::cat::cat::white_large_square:
:white_large_square::cat::white_large_square::white_large_square::white_large_square::cat::white_large_square::cat::cat::white_large_square::white_large_square::cat::white_large_square::white_large_square::cat::white_large_square::cat::white_large_square::cat::white_large_square:
:white_large_square::cat::white_large_square::white_large_square::white_large_square::cat::white_large_square::white_large_square::cat::white_large_square::white_large_square::cat::white_large_square::white_large_square::cat::white_large_square::white_large_square::white_large_square::cat::white_large_square:
:white_large_square::cat::cat::cat::white_large_square::cat::cat::cat::cat::white_large_square::white_large_square::cat::white_large_square::white_large_square::cat::white_large_square::white_large_square::white_large_square::cat::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:

**Review by ezhevita — APPROVED** [review]
cat approved 🐈

**Comment by keldranace** [comment]
LGBT

**Review by Iluvmagick — APPROVED** [review]
LGTM

**Pull request merged**
